#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm log*

runApplication surfaceFeatures

runApplication blockMesh

runApplication snappyHexMesh -overwrite

touch case.foam

echo Mesh created
echo
