#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Clean run time folders
restore0Dir

runApplication blockMesh

runApplication renumberMesh -overwrite

touch case.foam

# Mapping fields
mapFields -sourceTime latestTime ../pitzDailyRAS

runApplication $(getApplication)

# postProcess -func "mag(U)" -latestTime
# postProcess -func singleGraph -latestTime

echo
echo Case ended

